import React,{useCallback,useEffect,useState}from"react";
import{Alert,Modal,SafeAreaView,ScrollView,Text,View}from"react-native";
import{colors as C,money,supabase}from"./config";
import{Button,Field,Header,Stat,s}from"./ui";
import LiveVideo from"./LiveVideo";

export default function SellScreen({profile,user,flash}){
 const[title,setTitle]=useState(""),[productTitle,setProductTitle]=useState(""),[startingBid,setStartingBid]=useState(""),[weight,setWeight]=useState("8"),[length,setLength]=useState("8"),[width,setWidth]=useState("6"),[height,setHeight]=useState("4"),[host,setHost]=useState(null),[busy,setBusy]=useState(false),[stats,setStats]=useState({listings:0,live:0,ship:0});
 const load=useCallback(async()=>{const[{count:listings},{count:live},{count:ship}]=await Promise.all([supabase.from("products").select("id",{count:"exact",head:true}).eq("seller_id",user.id),supabase.from("shows").select("id",{count:"exact",head:true}).eq("seller_id",user.id).eq("status","live"),supabase.from("orders").select("id",{count:"exact",head:true}).eq("seller_id",user.id).in("status",["paid","packed"])]);setStats({listings:listings||0,live:live||0,ship:ship||0});},[user.id]);useEffect(()=>{load()},[load]);
 const request=async()=>{setBusy(true);const{error}=await supabase.rpc("request_seller_approval");setBusy(false);if(error)Alert.alert("Request failed",error.message);else{flash("Seller approval requested");Alert.alert("Request sent","An administrator can now approve your seller account.")}};
 const start=async()=>{if(!profile?.seller_approved)return Alert.alert("Approval required","Request seller approval first.");if(!profile?.shipping_address)return Alert.alert("Shipping address required","Open Account and save your shipping address first.");if(!profile?.stripe_onboarding_complete)return Alert.alert("Financial setup required","Open Account, complete Stripe financial setup, then refresh its status.");if(!title.trim()||!productTitle.trim()||!startingBid||![weight,length,width,height].every(v=>Number(v)>0))return Alert.alert("Missing information","Enter the show, product, bid and package measurements.");setBusy(true);const{data:product,error:pe}=await supabase.from("products").insert({seller_id:user.id,title:productTitle.trim(),starting_bid:Number(startingBid),price:Number(startingBid),status:"active",stock:1,weight_oz:Number(weight),length_in:Number(length),width_in:Number(width),height_in:Number(height)}).select().single();if(pe){setBusy(false);return Alert.alert("Product error",pe.message)}const room=`show_${user.id.replace(/-/g,"").slice(0,12)}_${Date.now()}`;const{data:show,error}=await supabase.from("shows").insert({seller_id:user.id,title:title.trim(),room_name:room,status:"live",starts_at:new Date().toISOString(),current_product_id:product.id}).select().single();setBusy(false);if(error)return Alert.alert("Show error",error.message);setHost({...show,product});flash("You are live");load()};
 return <ScrollView contentContainerStyle={s.page}><Header title="SELLER HUB" subtitle="Live auctions and today's tasks" profile={profile}/>{!profile?.seller_approved&&<View style={s.warning}><Text style={s.title}>Seller approval required</Text><Text style={s.muted}>Approved sellers receive a verified badge and can broadcast.</Text><Button title="Request seller approval" onPress={request}/></View>}<View style={s.panel}><Text style={s.section}>Start a live auction</Text><Field label="Show title" value={title} onChangeText={setTitle} placeholder="Dollar Start Drone Night"/><Field label="Product" value={productTitle} onChangeText={setProductTitle} placeholder="4K Foldable Camera Drone"/><Field label="Starting bid" value={startingBid} onChangeText={setStartingBid} keyboardType="decimal-pad" placeholder="1.00"/><View style={{minHeight:120,borderColor:C.muted,borderWidth:1,borderStyle:"dashed",borderRadius:16,alignItems:"center",justifyContent:"center",gap:6}}><Text style={{color:C.orange,fontSize:36}}>＋</Text><Text style={s.title}>Live-auction product</Text><Text style={s.muted}>Your camera is the show preview.</Text></View><Button disabled={busy||!profile?.seller_approved} title={busy?"Starting…":"Start camera & go live"} onPress={start}/></View><View style={s.panel}><Text style={s.section}>Today's tasks</Text><Stat label="Active listings" value={stats.listings}/><Stat label="Live shows" value={stats.live}/><Stat label="Orders to ship" value={stats.ship}/></View><Host show={host} user={user} onEnd={()=>{setHost(null);setTitle("");setProductTitle("");setStartingBid("");load()}}/></ScrollView>;
}
function Host({show,user,onEnd}){const[ending,setEnding]=useState(false);if(!show)return null;const end=async()=>{setEnding(true);const{data:winning}=await supabase.from("bids").select("bidder_id,amount").eq("show_id",show.id).order("amount",{ascending:false}).limit(1).maybeSingle();if(winning?.bidder_id)await supabase.from("orders").insert({buyer_id:winning.bidder_id,seller_id:user.id,product_id:show.product.id,total:winning.amount,status:"payment_due",payout_status:"held"});await supabase.from("shows").update({status:"ended",ended_at:new Date().toISOString()}).eq("id",show.id);setEnding(false);onEnd()};return <Modal visible animationType="slide"><SafeAreaView style={s.safe}><View style={s.modalHeader}><View style={{flex:1}}><Text style={s.logo}>YOU ARE LIVE</Text><Text style={s.muted}>{show.title}</Text></View><Text style={{color:C.red,fontWeight:"900"}}>● LIVE</Text></View><LiveVideo room={show.room_name} user={user} host/><View style={s.page}><Text style={s.logo}>{show.product.title}</Text><Text style={s.muted}>Your camera and microphone are broadcasting. Buyers can see this show on Home.</Text><Button danger disabled={ending} title={ending?"Ending…":"End auction"} onPress={end}/></View></SafeAreaView></Modal>}
