import React,{useCallback,useEffect,useState}from"react";
import{Alert,Modal,SafeAreaView,ScrollView,Text,View}from"react-native";
import{colors as C,money,supabase}from"./config";
import{Button,Field,Header,Stat,s}from"./ui";
import LiveVideo from"./LiveVideo";

export default function SellScreen({profile,user,flash}){
 const[title,setTitle]=useState(""),[host,setHost]=useState(null),[busy,setBusy]=useState(false),[stats,setStats]=useState({listings:0,live:0,ship:0});
 const load=useCallback(async()=>{const[{count:listings},{count:live},{count:ship}]=await Promise.all([supabase.from("products").select("id",{count:"exact",head:true}).eq("seller_id",user.id),supabase.from("shows").select("id",{count:"exact",head:true}).eq("seller_id",user.id).eq("status","live"),supabase.from("orders").select("id",{count:"exact",head:true}).eq("seller_id",user.id).in("status",["paid","packed"])]);setStats({listings:listings||0,live:live||0,ship:ship||0});},[user.id]);
 useEffect(()=>{load()},[load]);
 const request=async()=>{setBusy(true);const{error}=await supabase.rpc("request_seller_approval");setBusy(false);if(error)Alert.alert("Request failed",error.message);else{flash("Seller approval requested");Alert.alert("Request sent","An administrator can now approve your seller account.")}};
 const goLive=async()=>{if(!profile?.seller_approved)return Alert.alert("Approval required","Request seller approval first.");if(!profile?.shipping_address)return Alert.alert("Shipping address required","Open Account and save your shipping address first.");if(!profile?.stripe_onboarding_complete)return Alert.alert("Financial setup required","Open Account, complete Stripe financial setup, then refresh its status.");if(!title.trim())return Alert.alert("Show title required","Enter a title, then start the livestream.");setBusy(true);const room=`show_${user.id.replace(/-/g,"").slice(0,12)}_${Date.now()}`;const{data:show,error}=await supabase.from("shows").insert({seller_id:user.id,title:title.trim(),room_name:room,status:"live",starts_at:new Date().toISOString(),current_product_id:null}).select().single();setBusy(false);if(error)return Alert.alert("Show error",error.message);setHost(show);flash("You are live");load()};
 return <ScrollView contentContainerStyle={s.page}><Header title="SELLER HUB" subtitle="Go live, then auction products" profile={profile}/>{!profile?.seller_approved&&<View style={s.warning}><Text style={s.title}>Seller approval required</Text><Text style={s.muted}>Approved sellers receive a verified badge and can broadcast.</Text><Button title="Request seller approval" onPress={request}/></View>}<View style={s.panel}><Text style={s.section}>Start your livestream</Text><Field label="Show title" value={title} onChangeText={setTitle} placeholder="Dollar Start Drone Night"/><View style={{minHeight:120,borderColor:C.muted,borderWidth:1,borderStyle:"dashed",borderRadius:16,alignItems:"center",justifyContent:"center",gap:6}}><Text style={{color:C.orange,fontSize:36}}>◉</Text><Text style={s.title}>Camera and microphone</Text><Text style={s.muted}>Products are added after you are live.</Text></View><Button disabled={busy||!profile?.seller_approved} title={busy?"Starting…":"Start camera & go live"} onPress={goLive}/></View><View style={s.panel}><Text style={s.section}>Today's tasks</Text><Stat label="Active listings" value={stats.listings}/><Stat label="Live shows" value={stats.live}/><Stat label="Orders to ship" value={stats.ship}/></View>{host&&<Host show={host} user={user} flash={flash} onEnd={()=>{setHost(null);setTitle("");load()}}/>}</ScrollView>;
}

function Host({show,user,flash,onEnd}){
 const[product,setProduct]=useState(null),[menu,setMenu]=useState(false),[ending,setEnding]=useState(false),[busy,setBusy]=useState(false),[auctionEndsAt,setAuctionEndsAt]=useState(null),[secondsLeft,setSecondsLeft]=useState(0);
 const[productTitle,setProductTitle]=useState(""),[startingBid,setStartingBid]=useState(""),[duration,setDuration]=useState("15"),[weight,setWeight]=useState("8"),[length,setLength]=useState("8"),[width,setWidth]=useState("6"),[height,setHeight]=useState("4");
 const resetForm=()=>{setProductTitle("");setStartingBid("");setWeight("8");setLength("8");setWidth("6");setHeight("4")};
 const addProduct=async()=>{if(product)return Alert.alert("Auction already running","Wait for the current timer to reach zero.");if(!productTitle.trim()||!startingBid||Number(duration)<5||Number(duration)>300||![weight,length,width,height].every(v=>Number(v)>0))return Alert.alert("Missing information","Enter the product, starting bid, a timer from 5–300 seconds, and package measurements.");setBusy(true);const{data,error}=await supabase.from("products").insert({seller_id:user.id,title:productTitle.trim(),starting_bid:Number(startingBid),price:Number(startingBid),status:"active",stock:1,weight_oz:Number(weight),length_in:Number(length),width_in:Number(width),height_in:Number(height)}).select().single();if(!error){const ends=new Date(Date.now()+Number(duration)*1000).toISOString();const{error:updateError}=await supabase.from("shows").update({current_product_id:data.id,auction_ends_at:ends}).eq("id",show.id).eq("seller_id",user.id);if(updateError){setBusy(false);return Alert.alert("Auction error",updateError.message)}setProduct(data);setAuctionEndsAt(ends);setMenu(false);resetForm();flash(`${data.title} auction started`)}setBusy(false);if(error)Alert.alert("Product error",error.message)};
 const finishAuction=useCallback(async()=>{if(!product||busy)return;setBusy(true);const{data,error}=await supabase.rpc("finish_live_product_auction",{target_show:show.id,target_product:product.id});setBusy(false);if(error){if(error.message?.includes("still running"))return;return Alert.alert("Could not finish auction",error.message)}Alert.alert(data?.winner?"Auction sold":"Auction closed",data?.winner?`${product.title} sold for ${money(data.amount)}. Add the next product when ready.`:"There were no bids. Add the next product when ready.");setProduct(null);setAuctionEndsAt(null);setMenu(false)},[product,busy,show.id]);
 useEffect(()=>{if(!product||!auctionEndsAt)return;const tick=()=>{const left=Math.max(0,Math.ceil((new Date(auctionEndsAt).getTime()-Date.now())/1000));setSecondsLeft(left);if(left===0)finishAuction()};tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[product,auctionEndsAt,finishAuction]);
 useEffect(()=>{if(!product)return;const ch=supabase.channel(`host-clock-${show.id}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"shows",filter:`id=eq.${show.id}`},p=>{if(p.new.auction_ends_at)setAuctionEndsAt(p.new.auction_ends_at)}).subscribe();return()=>supabase.removeChannel(ch)},[product,show.id]);
 const endLive=async()=>{if(product)return Alert.alert("Auction in progress","Wait for the product countdown to finish before ending the livestream.");setEnding(true);const{error}=await supabase.from("shows").update({status:"ended",ended_at:new Date().toISOString(),current_product_id:null,auction_ends_at:null}).eq("id",show.id).eq("seller_id",user.id);setEnding(false);if(error)return Alert.alert("Could not end show",error.message);onEnd()};
 return <Modal visible animationType="slide" onRequestClose={()=>Alert.alert("Livestream active","Use End livestream before leaving.")}><SafeAreaView style={s.safe}><View style={s.modalHeader}><View style={{flex:1}}><Text style={s.logo}>YOU ARE LIVE</Text><Text style={s.muted}>{show.title}</Text></View><Text style={{color:C.red,fontWeight:"900"}}>● LIVE</Text></View><LiveVideo room={show.room_name} user={user} host/><ScrollView contentContainerStyle={[s.page,{paddingBottom:130}]}>{product?<View style={s.panel}><View style={s.between}><View><Text style={s.muted}>CURRENT AUCTION</Text><Text style={s.logo}>{product.title}</Text></View><Text style={{color:secondsLeft<=3?C.red:C.orange,fontSize:42,fontWeight:"900"}}>{secondsLeft}</Text></View><Text style={s.price}>Starts at {money(product.starting_bid)}</Text><Text style={s.muted}>The auction ends automatically at zero. Every accepted bid adds 3 seconds.</Text></View>:<View style={s.panel}><Text style={s.section}>No product running</Text><Text style={s.muted}>You are still live. Open Products below to start the next auction.</Text></View>}{menu&&!product&&<View style={s.panel}><Text style={s.section}>Add auction product</Text><Field label="Product" value={productTitle} onChangeText={setProductTitle} placeholder="4K Foldable Camera Drone"/><Field label="Starting bid" value={startingBid} onChangeText={setStartingBid} keyboardType="decimal-pad" placeholder="1.00"/><Field label="Auction timer (seconds)" value={duration} onChangeText={setDuration} keyboardType="number-pad" placeholder="15"/><Field label="Weight (oz)" value={weight} onChangeText={setWeight} keyboardType="decimal-pad"/><View style={s.row}><View style={{flex:1}}><Field label="Length" value={length} onChangeText={setLength} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Width" value={width} onChangeText={setWidth} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Height" value={height} onChangeText={setHeight} keyboardType="decimal-pad"/></View></View><Button disabled={busy} title={busy?"Starting auction…":"Start product auction"} onPress={addProduct}/></View>}</ScrollView><View style={[s.nav,{position:"absolute",left:0,right:0,bottom:0,paddingBottom:12}]}><View style={{flex:1,paddingHorizontal:8}}><Button ghost disabled={!!product} title={menu?"Close products":"＋ Products"} onPress={()=>setMenu(v=>!v)}/></View><View style={{flex:1,paddingHorizontal:8}}><Button danger disabled={ending||!!product} title={ending?"Ending…":"End livestream"} onPress={endLive}/></View></View></SafeAreaView></Modal>;
}
